version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports: 
      - '5432:5432'
    volumes:
      - ./createTables.sql:/docker-entrypoint-initdb.d/createTables.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    networks:
      - conectar

  backend:
    build: .
    ports:
      - '9000:80'
    volumes:
      - .:/app
    depends_on:
      - db   
    networks:
      - conectar

networks:
  conectar: