version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports: 
      - '5432:5432'
    volumes:
      - ./createTables.sql:/docker-entrypoint-initdb.d/createTables.sql
  
  backend:
    build: .
    ports:
      - '9000:5246'
    volumes:
      - .:/app
    depends_on:
      - db